name: Email Test
on:
  email:
    imap:
      host: imap.gmail.com
      user: actionsflowtest@gmail.com
      password: 7SFfp1GjG6tgviui
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          subject: ${{(on.email.outputs.subject)}}
        run: |
          echo subject: $subject