name: Email Test
on:
  email:
    imap:
      host: imap.gmail.com
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASSWORD}}
      port: 993
      tls: true
      tlsOptions: { rejectUnauthorized: false }
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          subject: ${{(on.email.outputs.subject)}}
        run: |
          echo subject: $subject creds ${{secrets.EMAIL_USER}} ${{secrets.EMAIL_PASSWORD}}